language: android

jdk:
# build-tools 25.0.0 need jdk8 or above.
- oraclejdk8
android:
  components:
    # Ref https://github.com/travis-ci/travis-ci/issues/6260.
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra

after_script:
    - cat ./app/build/outputs/lint-results.xml
    - cat ./library/build/outputs/lint-results.xml

sudo: false
